// <auto-generated />
namespace AVagas.Core.Data.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CoberetoOpcional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CoberetoOpcional));
        
        string IMigrationMetadata.Id
        {
            get { return "201405241410486_CoberetoOpcional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
